import {
  AirVent,
  Car,
  CalendarCheck,
  Cctv,
  Coffee,
  Dog,
  DoorOpen,
  Dumbbell,
  Flame,
  MapPin,
  Microwave,
  Refrigerator,
  ShowerHead,
  Snowflake,
  TreePine,
  Tv,
  Utensils,
  Waves,
  Wifi,
  type LucideIcon,
} from 'lucide-react';

export interface Room {
  id: string;
  title: string;
  location: string;
  address: string;
  roomType: string;
  images: string[];
  price: number;
  rating: number;
  reviewCount: number;
  distance: string;
  dateRange: string;
  isGuestFavorite: boolean;
  guests: number;
  bedrooms: number;
  beds: number;
  baths: number;
}

export interface RoomHost {
  name: string;
  avatar: string;
  isSuperhost: boolean;
  yearsHosting: number;
  reviewCount: number;
  responseRate: number;
}

export interface RoomReview {
  name: string;
  avatar: string;
  from: string;
  date: string;
  content: string;
}

export interface RoomAmenity {
  icon: LucideIcon;
  label: string;
}

/** 每筆房源 5 張圖，用固定 seed 讓每次重整都拿到同一批圖 */
const buildImages = (seed: string) =>
  Array.from(
    { length: 5 },
    (_, index) => `https://picsum.photos/seed/${seed}-${index + 1}/800/600`
  );

/** 費用明細用的全域固定金額（TWD） */
export const CLEANING_FEE = 1200;
export const SERVICE_FEE = 980;

/** 詳情頁評價區直接列出的筆數，超過就出「顯示全部」按鈕 */
export const REVIEW_PREVIEW_COUNT = 6;

/** 詳情頁各區塊的錨點 id，導覽列靠這些 id 做定位與捲動 */
export const ROOM_SECTION = {
  gallery: 'room-gallery',
  amenities: 'room-amenities',
  calendar: 'room-calendar',
  reviews: 'room-reviews',
  booking: 'room-booking',
};

export const rooms: Room[] = [
  {
    id: 'jeju-ocean-house',
    title: '面海第一排的濟州石屋，看得到日出',
    location: '南韓Gujwa-eup, Cheju',
    address: '南韓 濟州特別自治道 舊左邑',
    roomType: '整套獨棟房屋',
    images: buildImages('jeju-ocean-house'),
    price: 2708,
    rating: 4.84,
    reviewCount: 18,
    distance: '距離 1,079公里',
    dateRange: '2月8日至13日',
    isGuestFavorite: true,
    guests: 4,
    bedrooms: 2,
    beds: 3,
    baths: 1,
  },
  {
    id: 'taipei-daan-loft',
    title: '大安森林公園旁的採光挑高小宅',
    location: '台北市大安區',
    address: '台灣 台北市 大安區',
    roomType: '整套公寓',
    images: buildImages('taipei-daan-loft'),
    price: 3180,
    rating: 4.92,
    reviewCount: 24,
    distance: '距離 8公里',
    dateRange: '3月2日至6日',
    isGuestFavorite: true,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
  },
  {
    id: 'yilan-jiaoxi-onsen',
    title: '礁溪湯屋別墅，房內就有溫泉池',
    location: '宜蘭縣礁溪鄉',
    address: '台灣 宜蘭縣 礁溪鄉',
    roomType: '整套別墅',
    images: buildImages('yilan-jiaoxi-onsen'),
    price: 5460,
    rating: 4.76,
    reviewCount: 11,
    distance: '距離 42公里',
    dateRange: '2月18日至21日',
    isGuestFavorite: false,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
  },
  {
    id: 'hualien-cliff-villa',
    title: '花蓮海崖上的無邊際泳池villa',
    location: '花蓮縣豐濱鄉',
    address: '台灣 花蓮縣 豐濱鄉',
    roomType: '整套別墅',
    images: buildImages('hualien-cliff-villa'),
    price: 8920,
    rating: 4.95,
    reviewCount: 9,
    distance: '距離 156公里',
    dateRange: '4月5日至9日',
    isGuestFavorite: true,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
  },
  {
    id: 'kyoto-machiya',
    title: '祇園百年町家，走路五分鐘到八坂神社',
    location: '日本京都市東山區',
    address: '日本 京都府 京都市東山區',
    roomType: '整套獨棟房屋',
    images: buildImages('kyoto-machiya'),
    price: 6240,
    rating: 4.89,
    reviewCount: 22,
    distance: '距離 1,684公里',
    dateRange: '3月28日至4月2日',
    isGuestFavorite: true,
    guests: 5,
    bedrooms: 2,
    beds: 4,
    baths: 1,
  },
  {
    id: 'osaka-namba-flat',
    title: '難波站走路三分鐘，逛街吃飯都方便',
    location: '日本大阪市中央區',
    address: '日本 大阪府 大阪市中央區',
    roomType: '整套公寓',
    images: buildImages('osaka-namba-flat'),
    price: 3560,
    rating: 4.71,
    reviewCount: 20,
    distance: '距離 1,720公里',
    dateRange: '2月11日至15日',
    isGuestFavorite: false,
    guests: 4,
    bedrooms: 1,
    beds: 3,
    baths: 1,
  },
  {
    id: 'sapporo-snow-cabin',
    title: '札幌雪國木屋，冬天推開門就是雪景',
    location: '日本札幌市南區',
    address: '日本 北海道 札幌市南區',
    roomType: '整套小木屋',
    images: buildImages('sapporo-snow-cabin'),
    price: 4720,
    rating: 4.88,
    reviewCount: 14,
    distance: '距離 2,850公里',
    dateRange: '1月20日至25日',
    isGuestFavorite: true,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
  },
  {
    id: 'okinawa-beach-house',
    title: '恩納村海邊平房，走路到沙灘只要一分鐘',
    location: '日本沖繩縣恩納村',
    address: '日本 沖繩縣 國頭郡恩納村',
    roomType: '整套獨棟房屋',
    images: buildImages('okinawa-beach-house'),
    price: 5180,
    rating: 4.81,
    reviewCount: 16,
    distance: '距離 632公里',
    dateRange: '5月3日至8日',
    isGuestFavorite: false,
    guests: 6,
    bedrooms: 2,
    beds: 4,
    baths: 2,
  },
  {
    id: 'tainan-old-town',
    title: '台南老屋改建，一開窗就是紅磚巷弄',
    location: '台南市中西區',
    address: '台灣 台南市 中西區',
    roomType: '整套獨棟房屋',
    images: buildImages('tainan-old-town'),
    price: 2280,
    rating: 4.93,
    reviewCount: 23,
    distance: '距離 298公里',
    dateRange: '3月14日至17日',
    isGuestFavorite: true,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
  },
  {
    id: 'kenting-surf-hostel',
    title: '墾丁衝浪民宿，板子借你不加價',
    location: '屏東縣恆春鎮',
    address: '台灣 屏東縣 恆春鎮',
    roomType: '獨立房間',
    images: buildImages('kenting-surf-hostel'),
    price: 1480,
    rating: 4.62,
    reviewCount: 19,
    distance: '距離 380公里',
    dateRange: '6月7日至10日',
    isGuestFavorite: false,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
  },
  {
    id: 'taichung-art-apartment',
    title: '審計新村旁的藝術公寓，滿屋子老件',
    location: '台中市西區',
    address: '台灣 台中市 西區',
    roomType: '整套公寓',
    images: buildImages('taichung-art-apartment'),
    price: 2640,
    rating: 4.87,
    reviewCount: 13,
    distance: '距離 152公里',
    dateRange: '2月25日至28日',
    isGuestFavorite: true,
    guests: 4,
    bedrooms: 2,
    beds: 3,
    baths: 1,
  },
  {
    id: 'nantou-cingjing-cottage',
    title: '清境雲海鄉村小屋，早上有羊在門口',
    location: '南投縣仁愛鄉',
    address: '台灣 南投縣 仁愛鄉',
    roomType: '整套鄉村小屋',
    images: buildImages('nantou-cingjing-cottage'),
    price: 4380,
    rating: 4.79,
    reviewCount: 10,
    distance: '距離 196公里',
    dateRange: '4月18日至22日',
    isGuestFavorite: false,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
  },
  {
    id: 'hsinchu-hakka-yard',
    title: '北埔客家三合院，前庭有大棵老樹',
    location: '新竹縣北埔鄉',
    address: '台灣 新竹縣 北埔鄉',
    roomType: '整套獨棟房屋',
    images: buildImages('hsinchu-hakka-yard'),
    price: 3120,
    rating: 4.85,
    reviewCount: 8,
    distance: '距離 78公里',
    dateRange: '3月8日至11日',
    isGuestFavorite: true,
    guests: 8,
    bedrooms: 4,
    beds: 6,
    baths: 2,
  },
  {
    id: 'penghu-island-suite',
    title: '馬公港邊白色套房，看得到跨海大橋',
    location: '澎湖縣馬公市',
    address: '台灣 澎湖縣 馬公市',
    roomType: '整套公寓',
    images: buildImages('penghu-island-suite'),
    price: 2960,
    rating: 4.74,
    reviewCount: 12,
    distance: '距離 302公里',
    dateRange: '7月2日至6日',
    isGuestFavorite: false,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
  },
  {
    id: 'busan-haeundae-view',
    title: '海雲台高樓層海景房，夜景整片攤在窗前',
    location: '南韓釜山海雲台區',
    address: '南韓 釜山廣域市 海雲台區',
    roomType: '整套公寓',
    images: buildImages('busan-haeundae-view'),
    price: 4260,
    rating: 4.83,
    reviewCount: 21,
    distance: '距離 1,552公里',
    dateRange: '5月16日至20日',
    isGuestFavorite: true,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
  },
  {
    id: 'seoul-hongdae-studio',
    title: '弘大巷弄裡的小套房，出門就是咖啡廳',
    location: '南韓首爾麻浦區',
    address: '南韓 首爾特別市 麻浦區',
    roomType: '整套公寓',
    images: buildImages('seoul-hongdae-studio'),
    price: 2840,
    rating: 4.68,
    reviewCount: 24,
    distance: '距離 1,478公里',
    dateRange: '4月9日至13日',
    isGuestFavorite: false,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
  },
  {
    id: 'chiangmai-jungle-villa',
    title: '清邁叢林泳池villa，四周只有蟲鳴',
    location: '泰國清邁市',
    address: '泰國 清邁府 清邁市',
    roomType: '整套別墅',
    images: buildImages('chiangmai-jungle-villa'),
    price: 3980,
    rating: 4.91,
    reviewCount: 15,
    distance: '距離 2,560公里',
    dateRange: '11月12日至18日',
    isGuestFavorite: true,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
  },
  {
    id: 'bangkok-riverside',
    title: '昭披耶河畔公寓，陽台看得到夜船',
    location: '泰國曼谷市',
    address: '泰國 曼谷市 邦拉區',
    roomType: '整套公寓',
    images: buildImages('bangkok-riverside'),
    price: 2460,
    rating: 4.77,
    reviewCount: 17,
    distance: '距離 2,510公里',
    dateRange: '12月3日至8日',
    isGuestFavorite: false,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
  },
  {
    id: 'bali-ubud-treehouse',
    title: '烏布梯田樹屋，早餐送到房間陽台',
    location: '印尼峇里島烏布',
    address: '印尼 峇里省 吉安雅縣烏布',
    roomType: '整套樹屋',
    images: buildImages('bali-ubud-treehouse'),
    price: 4640,
    rating: 4.96,
    reviewCount: 20,
    distance: '距離 3,890公里',
    dateRange: '8月20日至26日',
    isGuestFavorite: true,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
  },
  {
    id: 'singapore-marina-flat',
    title: '濱海灣正對面，跨年煙火不用出門看',
    location: '新加坡濱海灣',
    address: '新加坡 濱海灣',
    roomType: '整套公寓',
    images: buildImages('singapore-marina-flat'),
    price: 7320,
    rating: 4.72,
    reviewCount: 14,
    distance: '距離 3,240公里',
    dateRange: '12月29日至1月2日',
    isGuestFavorite: false,
    guests: 4,
    bedrooms: 2,
    beds: 3,
    baths: 2,
  },
  {
    id: 'hongkong-central-nest',
    title: '中環半山小宅，麻雀雖小但收納滿分',
    location: '香港中環',
    address: '中國香港特別行政區 中西區',
    roomType: '整套公寓',
    images: buildImages('hongkong-central-nest'),
    price: 3860,
    rating: 4.65,
    reviewCount: 18,
    distance: '距離 806公里',
    dateRange: '3月21日至24日',
    isGuestFavorite: false,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
  },
  {
    id: 'danang-beach-loft',
    title: '峴港美溪海灘挑高樓中樓',
    location: '越南峴港市',
    address: '越南 峴港市 山茶郡',
    roomType: '整套公寓',
    images: buildImages('danang-beach-loft'),
    price: 2120,
    rating: 4.86,
    reviewCount: 16,
    distance: '距離 1,940公里',
    dateRange: '9月5日至10日',
    isGuestFavorite: true,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
  },
  {
    id: 'taitung-rift-valley',
    title: '鹿野縱谷玻璃屋，晚上躺著看銀河',
    location: '台東縣鹿野鄉',
    address: '台灣 台東縣 鹿野鄉',
    roomType: '整套獨棟房屋',
    images: buildImages('taitung-rift-valley'),
    price: 3740,
    rating: 4.9,
    reviewCount: 9,
    distance: '距離 286公里',
    dateRange: '6月18日至22日',
    isGuestFavorite: true,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
  },
  {
    id: 'alishan-tea-house',
    title: '阿里山茶園裡的檜木老屋，清晨有雲海',
    location: '嘉義縣阿里山鄉',
    address: '台灣 嘉義縣 阿里山鄉',
    roomType: '整套獨棟房屋',
    images: buildImages('alishan-tea-house'),
    price: 3420,
    rating: 4.82,
    reviewCount: 12,
    distance: '距離 254公里',
    dateRange: '10月11日至15日',
    isGuestFavorite: false,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
  },
];

/** 以下為詳情頁共用的內容池，依房源在清單中的順序輪流取用 */
const descriptions = [
  '整棟空間都是你的，沒有其他房客。客廳的落地窗從早到晚都有光，午後可以窩在窗邊那張舊沙發上發呆。廚房備有基本調味料與鍋具，想自己煮一頓也沒問題。\n\n房子離最近的便利商店走路約六分鐘，巷口有一間開很久的早餐店，老闆娘六點就開門。',
  '這裡原本是老屋，我們花了一年半慢慢整理，保留了原本的地磚與木窗框，其餘全部重做。空調、熱水、Wi-Fi 都是新的，住起來不會有老房子的不便。\n\n二樓的房間比較安靜，適合早睡的人；一樓靠馬路，白天會有一點市場的聲音，我們覺得那正是這一帶的樣子。',
  '房子座落在坡地上，客廳外的平台是整間屋子最好的位置，天氣好的時候可以看到遠方的稜線。晚上光害很少，抬頭就看得到星星。\n\n提醒你，上山的最後一段路比較窄，開車請放慢速度。我們也可以幫忙安排接送。',
  '走路五分鐘可以到車站，附近吃的很多，晚上十一點還找得到宵夜。房子雖然不大，但收納都做好了，行李箱可以完全攤開放。\n\n適合第一次來這裡自由行的旅客，出入方便，不用一直搬行李。',
  '整層四房兩廳，一大家子出遊剛剛好。餐桌可以坐八個人，我們常收到房客在這裡吃火鍋的照片。院子裡有烤肉架，用完幫忙沖一下就好。\n\n屋內全面禁菸，抽菸請到院子。有帶小朋友的話樓梯口有安全門可以扣上。',
  '這間房間面海，早上不用鬧鐘，天亮光線就會把你叫醒。沙灘走路一分鐘，浮潛用具房內免費借用。\n\n夏天的午後偶爾會有陣雨，記得帶件薄外套。海邊風大，曬衣服請夾好。',
];

const amenities: RoomAmenity[] = [
  { icon: Wifi, label: '無線網路' },
  { icon: Tv, label: '電視' },
  { icon: AirVent, label: '冷氣' },
  { icon: Utensils, label: '廚房' },
  { icon: Refrigerator, label: '冰箱' },
  { icon: Microwave, label: '微波爐' },
  { icon: Coffee, label: '咖啡機' },
  { icon: ShowerHead, label: '沐浴用品' },
  { icon: Car, label: '免費停車位' },
  { icon: Waves, label: '泳池' },
  { icon: TreePine, label: '庭院' },
  { icon: Flame, label: '烤肉設備' },
  { icon: Dumbbell, label: '健身房' },
  { icon: Snowflake, label: '洗烘衣機' },
  { icon: Dog, label: '可攜帶寵物' },
  { icon: Cctv, label: '門口監視器' },
];

export const highlights = [
  {
    icon: DoorOpen,
    title: '自助入住',
    description: '用密碼鎖自行入住，不用等房東。',
  },
  {
    icon: MapPin,
    title: '絕佳位置',
    description: '最近 90% 的房客給了五星位置評分。',
  },
  {
    icon: CalendarCheck,
    title: '免費取消',
    description: '入住前 5 天以前取消，全額退款。',
  },
];

const hosts: RoomHost[] = [
  {
    name: '怡君',
    avatar: 'https://picsum.photos/seed/host-yijun/200/200',
    isSuperhost: true,
    yearsHosting: 6,
    reviewCount: 412,
    responseRate: 100,
  },
  {
    name: 'Kenji',
    avatar: 'https://picsum.photos/seed/host-kenji/200/200',
    isSuperhost: true,
    yearsHosting: 9,
    reviewCount: 1268,
    responseRate: 98,
  },
  {
    name: '文彥',
    avatar: 'https://picsum.photos/seed/host-wenyen/200/200',
    isSuperhost: false,
    yearsHosting: 2,
    reviewCount: 87,
    responseRate: 92,
  },
  {
    name: 'Soo-min',
    avatar: 'https://picsum.photos/seed/host-soomin/200/200',
    isSuperhost: true,
    yearsHosting: 4,
    reviewCount: 335,
    responseRate: 100,
  },
  {
    name: '阿德',
    avatar: 'https://picsum.photos/seed/host-ade/200/200',
    isSuperhost: false,
    yearsHosting: 3,
    reviewCount: 129,
    responseRate: 95,
  },
  {
    name: 'Nadia',
    avatar: 'https://picsum.photos/seed/host-nadia/200/200',
    isSuperhost: true,
    yearsHosting: 7,
    reviewCount: 604,
    responseRate: 99,
  },
];

const reviews: RoomReview[] = [
  {
    name: '雅雯',
    avatar: 'https://picsum.photos/seed/review-yawen/120/120',
    from: '台北市',
    date: '2026年6月',
    content: '照片跟實際完全一樣，甚至更好。房東回訊息很快，入住流程也很清楚，下次還會再來。',
  },
  {
    name: 'Marcus',
    avatar: 'https://picsum.photos/seed/review-marcus/120/120',
    from: '雪梨',
    date: '2026年5月',
    content: '位置無可挑剔，走路就能到所有想去的地方。房子很乾淨，床墊軟硬適中，睡得很好。',
  },
  {
    name: '子豪',
    avatar: 'https://picsum.photos/seed/review-zihao/120/120',
    from: '高雄市',
    date: '2026年5月',
    content: '一家五口住起來很寬敞，廚房設備齊全，我們自己煮了兩餐。唯一小缺點是隔壁早上有點吵。',
  },
  {
    name: 'Hana',
    avatar: 'https://picsum.photos/seed/review-hana/120/120',
    from: '東京',
    date: '2026年4月',
    content: '房東準備了在地的餐廳清單，超級實用。空間比想像中大，行李攤開也不會擋路。',
  },
  {
    name: '佩珊',
    avatar: 'https://picsum.photos/seed/review-peishan/120/120',
    from: '台中市',
    date: '2026年4月',
    content: '很有味道的一間房子，細節看得出來有用心。熱水穩定、水壓也夠，這點對我來說很加分。',
  },
  {
    name: 'Daniel',
    avatar: 'https://picsum.photos/seed/review-daniel/120/120',
    from: '新加坡',
    date: '2026年3月',
    content: '值回票價。景色真的漂亮，晚上坐在外面吹風就待了一小時。停車位也很好停。',
  },
  {
    name: '宥廷',
    avatar: 'https://picsum.photos/seed/review-youting/120/120',
    from: '新北市',
    date: '2026年3月',
    content: '訂房到入住整個過程都很順，密碼鎖很方便，半夜到也不用麻煩房東。',
  },
  {
    name: 'Ji-woo',
    avatar: 'https://picsum.photos/seed/review-jiwoo/120/120',
    from: '首爾',
    date: '2026年2月',
    content: '很安靜，適合想好好休息的人。附近有超市，補給很方便。推薦給情侶或小家庭。',
  },
  {
    name: '思婷',
    avatar: 'https://picsum.photos/seed/review-siting/120/120',
    from: '桃園市',
    date: '2026年2月',
    content: '打掃得非常乾淨，備品也齊全，連洗衣精都準備好了。房東很細心。',
  },
  {
    name: 'Oliver',
    avatar: 'https://picsum.photos/seed/review-oliver/120/120',
    from: '倫敦',
    date: '2026年1月',
    content: '空間感很好，採光是重點。工作了一整天回來，坐在窗邊很放鬆。網路速度也夠快。',
  },
  {
    name: '柏翰',
    avatar: 'https://picsum.photos/seed/review-bohan/120/120',
    from: '台南市',
    date: '2026年1月',
    content: '朋友揪團出遊住這裡剛剛好，客廳夠大，我們玩桌遊玩到半夜。記得音量要控制一下。',
  },
  {
    name: 'Aiko',
    avatar: 'https://picsum.photos/seed/review-aiko/120/120',
    from: '大阪',
    date: '2025年12月',
    content: '第二次入住了，還是一樣舒服。房東每次都會留一張手寫小卡，這種小細節讓人很有印象。',
  },
  {
    name: '冠儒',
    avatar: 'https://picsum.photos/seed/review-guanru/120/120',
    from: '基隆市',
    date: '2025年12月',
    content: '停車超方便，這對開車來的人真的很重要。屋內動線順，兩個人住剛剛好。',
  },
  {
    name: 'Emma',
    avatar: 'https://picsum.photos/seed/review-emma/120/120',
    from: '墨爾本',
    date: '2025年11月',
    content: '房東給的建議都很在地，不是網路上找得到的那種。照著吃了兩間店，都很好吃。',
  },
  {
    name: '雅琪',
    avatar: 'https://picsum.photos/seed/review-yachi/120/120',
    from: '嘉義市',
    date: '2025年11月',
    content: '床單枕頭都很新，睡起來很安心。浴室乾濕分離，帶小孩洗澡不用怕滑倒。',
  },
  {
    name: 'Takeshi',
    avatar: 'https://picsum.photos/seed/review-takeshi/120/120',
    from: '名古屋',
    date: '2025年10月',
    content: '空間跟照片一致，沒有落差。入住說明寫得很清楚，第一次用密碼鎖也沒卡關。',
  },
  {
    name: '思妤',
    avatar: 'https://picsum.photos/seed/review-siyu/120/120',
    from: '彰化縣',
    date: '2025年10月',
    content: '很喜歡客廳那面窗，下午的光線超美。唯一建議是廚房刀具可以再利一點。',
  },
  {
    name: 'Lucas',
    avatar: 'https://picsum.photos/seed/review-lucas/120/120',
    from: '溫哥華',
    date: '2025年9月',
    content: '安靜到可以睡到自然醒。附近走十分鐘有市場，早上去逛很有意思。',
  },
  {
    name: '育誠',
    avatar: 'https://picsum.photos/seed/review-yucheng/120/120',
    from: '苗栗縣',
    date: '2025年9月',
    content: '房東事前就把注意事項都講清楚，入住完全沒有意外。整潔度給滿分。',
  },
  {
    name: 'Mei',
    avatar: 'https://picsum.photos/seed/review-mei/120/120',
    from: '福岡',
    date: '2025年8月',
    content: '一個人來出差住這裡剛好，桌子夠大可以工作，網路也很穩。會再回訪。',
  },
  {
    name: '婉茹',
    avatar: 'https://picsum.photos/seed/review-wanru/120/120',
    from: '雲林縣',
    date: '2025年8月',
    content: '帶爸媽來住，他們一直說這裡舒服。有電梯這點對長輩來說真的差很多。',
  },
  {
    name: 'Noah',
    avatar: 'https://picsum.photos/seed/review-noah/120/120',
    from: '柏林',
    date: '2025年7月',
    content: '性價比很高，同樣價位很難找到這種條件。房東回訊息幾乎是秒回。',
  },
  {
    name: '孟璇',
    avatar: 'https://picsum.photos/seed/review-mengsuan/120/120',
    from: '花蓮縣',
    date: '2025年7月',
    content: '陽台的視野是意外驚喜，傍晚坐在那邊喝杯東西就很滿足。下次想住久一點。',
  },
];

const ratingCategories = [
  { label: '清潔度', offset: 0.06 },
  { label: '準確度', offset: -0.04 },
  { label: '入住', offset: 0.1 },
  { label: '溝通', offset: 0.02 },
  { label: '位置', offset: -0.08 },
  { label: '超值程度', offset: -0.12 },
];

/** 從指定位置開始輪流取用，讓每間房拿到的內容不同 */
const rotate = <T,>(list: T[], offset: number) => {
  const start = offset % list.length;
  return [...list.slice(start), ...list.slice(0, start)];
};

export const getRoomById = (id: string) => rooms.find((room) => room.id === id);

export const getRoomDetail = (room: Room) => {
  const index = Math.max(
    rooms.findIndex((item) => item.id === room.id),
    0
  );

  const rotatedReviews = rotate(reviews, index);

  return {
    description: descriptions[index % descriptions.length],
    amenities: rotate(amenities, index).slice(0, 10),
    host: hosts[index % hosts.length],
    // 這間房的完整評價，最多就是評論池的長度
    allReviews: rotatedReviews.slice(0, room.reviewCount),
    ratingScores: ratingCategories.map((category) => ({
      label: category.label,
      score: Math.min(5, Number((room.rating + category.offset).toFixed(1))),
    })),
  };
};
