import { TabList } from '@/app/components/Footer/FooterTabArea';

export const footerTabList: TabList[] = [
  {
    id: 'popular',
    value: '熱門',
    subMenu: [
      { title: '坎莫爾', type: '私有公寓' },
      { title: '貝納爾馬德納', type: '公寓' },
      { title: '馬貝拉', type: '獨棟房屋' },
      { title: '米納斯', type: '獨棟房屋' },
      { title: '普雷斯科特', type: '小木屋' },
      { title: '斯科茨代爾', type: '寵物友善房源' },
      { title: '圖森', type: '寵物友善房源' },
      { title: '賈斯珀', type: '小木屋' },
      { title: '山景城', type: '適合家庭入住的房源' },
      { title: 'Devonport', type: '鄉村小屋' },
      { title: 'Mallacoota', type: '海邊獨棟房屋' },
      { title: '伊比薩', type: '度假屋' },
      { title: '阿納海姆', type: '公寓' },
      { title: '蒙特雷', type: '鄉村小屋' },
      { title: '百索羅布', type: '度假屋' },
      { title: '聖巴巴拉', type: '寵物友善房源' },
      { title: '索諾瑪', type: '獨棟房屋' },
      { title: '拉塞雷納', type: '海景房源' },
      { title: '杜拜', type: '獨棟房屋' },
      { title: '伯明翰', type: '公寓' },
    ],
  },
  { id: 'art', value: '藝術與文化', subMenu: [
    { title: '鳳凰城', type: '私有公寓' },
    { title: '溫泉', type: '私有公寓' },
    { title: '洛杉磯', type: '豪宅' },
    { title: '聖地牙哥', type: '公寓' },
    { title: '舊金山', type: '度假屋' },
    { title: '巴塞隆納', type: '度假屋' },
    { title: '布拉格', type: '度假屋' },
    { title: '華盛頓', type: '公寓' },
    { title: '凱西克', type: '鄉村小屋' },
    { title: '倫敦', type: '獨棟房屋' },
    { title: '士嘉堡', type: '度假屋' },
    { title: 'Sherwood Forest', type: '小木屋' },
    { title: '約克', type: '寵物友善房源' },
    { title: '巴黎', type: '配備泳池的房源' },
    { title: '羅德', type: '配備泳池的房源' },
    { title: '那什維爾', type: '度假屋' },
    { title: '都柏林', type: '公寓' },
    { title: '佛羅倫斯', type: '私有公寓' },
    { title: '羅馬', type: '公寓' },
    { title: '里斯本', type: '海景房源' },
  ] },
  // { id: 'outdoor', value: '戶外', subMenu: [] },
  // { id: 'mountain', value: '山區', subMenu: [] },
  // { id: 'sea', value: '海邊', subMenu: [] },
  // { id: 'type', value: '類型', subMenu: [] },
  // { id: 'fun', value: '好玩新鮮事', subMenu: [] },
];
